<?php

global $google_fonts;

$google_fonts = array(
    array('label' => 'use theme default', 'value' => 'none'),
    array('label' => 'Abel', 'value' => 'Abel'),
    array('label' => 'Abril Fatface', 'value' => 'Abril+Fatface'),
    array('label' => 'Aclonica', 'value' => 'Aclonica'),
    array('label' => 'Actor', 'value' => 'Actor'),
    array('label' => 'Adamina', 'value' => 'Adamina'),
    array('label' => 'Aguafina Script', 'value' => 'Aguafina+Script'),
    array('label' => 'Aladin', 'value' => 'Aladin'),
    array('label' => 'Aldrich', 'value' => 'Aldrich'),
    array('label' => 'Alice', 'value' => 'Alice'),
    array('label' => 'Alike Angular', 'value' => 'Alike+Angular'),
    array('label' => 'Alike', 'value' => 'Alike'),
    array('label' => 'Allan', 'value' => 'Allan'),
    array('label' => 'Allerta Stencil', 'value' => 'Allerta+Stencil'),
    array('label' => 'Allerta', 'value' => 'Allerta'),
    array('label' => 'Amaranth', 'value' => 'Amaranth'),
    array('label' => 'Amatic SC', 'value' => 'Amatic+SC'),
    array('label' => 'Andada', 'value' => 'Andada'),
    array('label' => 'Andika', 'value' => 'Andika'),
    array('label' => 'Annie Use Your Telescope', 'value' => 'Annie+Use+Your+Telescope'),
    array('label' => 'Anonymous Pro', 'value' => 'Anonymous+Pro'),
    array('label' => 'Antic', 'value' => 'Antic'),
    array('label' => 'Anton', 'value' => 'Anton'),
    array('label' => 'Arapey', 'value' => 'Arapey'),
    array('label' => 'Architects Daughter', 'value' => 'Architects+Daughter'),
    array('label' => 'Arimo', 'value' => 'Arimo'),
    array('label' => 'Artifika', 'value' => 'Artifika'),
    array('label' => 'Arvo', 'value' => 'Arvo'),
    array('label' => 'Asset', 'value' => 'Asset'),
    array('label' => 'Astloch', 'value' => 'Astloch'),
    array('label' => 'Atomic Age', 'value' => 'Atomic+Age'),
    array('label' => 'Aubrey', 'value' => 'Aubrey'),
    array('label' => 'Bangers', 'value' => 'Bangers'),
    array('label' => 'Bentham', 'value' => 'Bentham'),
    array('label' => 'Bevan', 'value' => 'Bevan'),
    array('label' => 'Bigshot One', 'value' => 'Bigshot+One'),
    array('label' => 'Bitter', 'value' => 'Bitter'),
    array('label' => 'Black Ops One', 'value' => 'Black+Ops+One'),
    array('label' => 'Bowlby One SC', 'value' => 'Bowlby+One+SC'),
    array('label' => 'Bowlby One', 'value' => 'Bowlby+One'),
    array('label' => 'Brawler', 'value' => 'Brawler'),
    array('label' => 'Bubblegum Sans', 'value' => 'Bubblegum+Sans'),
    array('label' => 'Buda', 'value' => 'Buda'),
    array('label' => 'Butcherman Caps', 'value' => 'Butcherman+Caps'),
    array('label' => 'Cabin Condensed', 'value' => 'Cabin+Condensed'),
    array('label' => 'Cabin Sketch', 'value' => 'Cabin+Sketch'),
    array('label' => 'Cabin', 'value' => 'Cabin'),
    array('label' => 'Cagliostro', 'value' => 'Cagliostro'),
    array('label' => 'Calligraffitti', 'value' => 'Calligraffitti'),
    array('label' => 'Candal', 'value' => 'Candal'),
    array('label' => 'Cantarell', 'value' => 'Cantarell'),
    array('label' => 'Cardo', 'value' => 'Cardo'),
    array('label' => 'Carme', 'value' => 'Carme'),
    array('label' => 'Carter One', 'value' => 'Carter+One'),
    array('label' => 'Caudex', 'value' => 'Caudex'),
    array('label' => 'Cedarville Cursive', 'value' => 'Cedarville+Cursive'),
    array('label' => 'Changa One', 'value' => 'Changa+One'),
    array('label' => 'Cherry Cream Soda', 'value' => 'Cherry+Cream+Soda'),
    array('label' => 'Chewy', 'value' => 'Chewy'),
    array('label' => 'Chicle', 'value' => 'Chicle'),
    array('label' => 'Chivo', 'value' => 'Chivo'),
    array('label' => 'Coda Caption', 'value' => 'Coda+Caption'),
    array('label' => 'Coda', 'value' => 'Coda'),
    array('label' => 'Comfortaa', 'value' => 'Comfortaa'),
    array('label' => 'Coming Soon', 'value' => 'Coming+Soon'),
    array('label' => 'Contrail One', 'value' => 'Contrail+One'),
    array('label' => 'Convergence', 'value' => 'Convergence'),
    array('label' => 'Cookie', 'value' => 'Cookie'),
    array('label' => 'Copse', 'value' => 'Copse'),
    array('label' => 'Corben', 'value' => 'Corben'),
    array('label' => 'Cousine', 'value' => 'Cousine'),
    array('label' => 'Coustard', 'value' => 'Coustard'),
    array('label' => 'Covered By Your Grace', 'value' => 'Covered+By+Your+Grace'),
    array('label' => 'Crafty Girls', 'value' => 'Crafty+Girls'),
    array('label' => 'Creepster Caps', 'value' => 'Creepster+Caps'),
    array('label' => 'Crimson Text', 'value' => 'Crimson+Text'),
    array('label' => 'Crushed', 'value' => 'Crushed'),
    array('label' => 'Cuprum', 'value' => 'Cuprum'),
    array('label' => 'Damion', 'value' => 'Damion'),
    array('label' => 'Dancing Script', 'value' => 'Dancing+Script'),
    array('label' => 'Dawning of a New Day', 'value' => 'Dawning+of+a+New+Day'),
    array('label' => 'Days One', 'value' => 'Days+One'),
    array('label' => 'Delius Swash Caps', 'value' => 'Delius+Swash+Caps'),
    array('label' => 'Delius Unicase', 'value' => 'Delius+Unicase'),
    array('label' => 'Delius', 'value' => 'Delius'),
    array('label' => 'Devonshire', 'value' => 'Devonshire'),
    array('label' => 'Didact Gothic', 'value' => 'Didact+Gothic'),
    array('label' => 'Dorsa', 'value' => 'Dorsa'),
    array('label' => 'Dr Sugiyama', 'value' => 'Dr+Sugiyama'),
    array('label' => 'Droid Sans Mono', 'value' => 'Droid+Sans+Mono'),
    array('label' => 'Droid Sans', 'value' => 'Droid+Sans'),
    array('label' => 'Droid Serif', 'value' => 'Droid+Serif'),
    array('label' => 'EB Garamond', 'value' => 'EB+Garamond'),
    array('label' => 'Eater Caps', 'value' => 'Eater+Caps'),
    array('label' => 'Expletus Sans', 'value' => 'Expletus+Sans'),
    array('label' => 'Fanwood Text', 'value' => 'Fanwood+Text'),
    array('label' => 'Federant', 'value' => 'Federant'),
    array('label' => 'Federo', 'value' => 'Federo'),
    array('label' => 'Fjord One', 'value' => 'Fjord+One'),
    array('label' => 'Fondamento', 'value' => 'Fondamento'),
    array('label' => 'Fontdiner Swanky', 'value' => 'Fontdiner+Swanky'),
    array('label' => 'Forum', 'value' => 'Forum'),
    array('label' => 'Francois One', 'value' => 'Francois+One'),
    array('label' => 'Gentium Basic', 'value' => 'Gentium+Basic'),
    array('label' => 'Gentium Book Basic', 'value' => 'Gentium+Book+Basic'),
    array('label' => 'Geo', 'value' => 'Geo'),
    array('label' => 'Geostar Fill', 'value' => 'Geostar+Fill'),
    array('label' => 'Geostar', 'value' => 'Geostar'),
    array('label' => 'Give You Glory', 'value' => 'Give+You+Glory'),
    array('label' => 'Gloria Hallelujah', 'value' => 'Gloria+Hallelujah'),
    array('label' => 'Goblin One', 'value' => 'Goblin+One'),
    array('label' => 'Gochi Hand', 'value' => 'Gochi+Hand'),
    array('label' => 'Goudy Bookletter 1911', 'value' => 'Goudy+Bookletter+1911'),
    array('label' => 'Gravitas One', 'value' => 'Gravitas+One'),
    array('label' => 'Gruppo', 'value' => 'Gruppo'),
    array('label' => 'Hammersmith One', 'value' => 'Hammersmith+One'),
    array('label' => 'Herr Von Muellerhoff', 'value' => 'Herr+Von+Muellerhoff'),
    array('label' => 'Holtwood One SC', 'value' => 'Holtwood+One+SC'),
    array('label' => 'Homemade Apple', 'value' => 'Homemade+Apple'),
    array('label' => 'IM Fell DW Pica SC', 'value' => 'IM+Fell+DW+Pica+SC'),
    array('label' => 'IM Fell DW Pica', 'value' => 'IM+Fell+DW+Pica'),
    array('label' => 'IM Fell Double Pica SC', 'value' => 'IM+Fell+Double+Pica+SC'),
    array('label' => 'IM Fell Double Pica', 'value' => 'IM+Fell+Double+Pica'),
    array('label' => 'IM Fell English SC', 'value' => 'IM+Fell+English+SC'),
    array('label' => 'IM Fell English', 'value' => 'IM+Fell+English'),
    array('label' => 'IM Fell French Canon SC', 'value' => 'IM+Fell+French+Canon+SC'),
    array('label' => 'IM Fell French Canon', 'value' => 'IM+Fell+French+Canon'),
    array('label' => 'IM Fell Great Primer SC', 'value' => 'IM+Fell+Great+Primer+SC'),
    array('label' => 'IM Fell Great Primer', 'value' => 'IM+Fell+Great+Primer'),
    array('label' => 'Iceland', 'value' => 'Iceland'),
    array('label' => 'Inconsolata', 'value' => 'Inconsolata'),
    array('label' => 'Indie Flower', 'value' => 'Indie+Flower'),
    array('label' => 'Irish Grover', 'value' => 'Irish+Grover'),
    array('label' => 'Istok Web', 'value' => 'Istok+Web'),
    array('label' => 'Jockey One', 'value' => 'Jockey+One'),
    array('label' => 'Josefin Sans', 'value' => 'Josefin+Sans'),
    array('label' => 'Josefin Slab', 'value' => 'Josefin+Slab'),
    array('label' => 'Judson', 'value' => 'Judson'),
    array('label' => 'Julee', 'value' => 'Julee'),
    array('label' => 'Jura', 'value' => 'Jura'),
    array('label' => 'Just Another Hand', 'value' => 'Just+Another+Hand'),
    array('label' => 'Just Me Again Down Here', 'value' => 'Just+Me+Again+Down+Here'),
    array('label' => 'Kameron', 'value' => 'Kameron'),
    array('label' => 'Kelly Slab', 'value' => 'Kelly+Slab'),
    array('label' => 'Kenia', 'value' => 'Kenia'),
    array('label' => 'Knewave', 'value' => 'Knewave'),
    array('label' => 'Kranky', 'value' => 'Kranky'),
    array('label' => 'Kreon', 'value' => 'Kreon'),
    array('label' => 'Kristi', 'value' => 'Kristi'),
    array('label' => 'La Belle Aurore', 'value' => 'La+Belle+Aurore'),
    array('label' => 'Lancelot', 'value' => 'Lancelot'),
    array('label' => 'Lato', 'value' => 'Lato'),
    array('label' => 'League Script', 'value' => 'League+Script'),
    array('label' => 'Leckerli One', 'value' => 'Leckerli+One'),
    array('label' => 'Lekton', 'value' => 'Lekton'),
    array('label' => 'Lemon', 'value' => 'Lemon'),
    array('label' => 'Limelight', 'value' => 'Limelight'),
    array('label' => 'Linden Hill', 'value' => 'Linden+Hill'),
    array('label' => 'Lobster Two', 'value' => 'Lobster+Two'),
    array('label' => 'Lobster', 'value' => 'Lobster'),
    array('label' => 'Lora', 'value' => 'Lora'),
    array('label' => 'Love Ya Like A Sister', 'value' => 'Love+Ya+Like+A+Sister'),
    array('label' => 'Loved by the King', 'value' => 'Loved+by+the+King'),
    array('label' => 'Luckiest Guy', 'value' => 'Luckiest+Guy'),
    array('label' => 'Maiden Orange', 'value' => 'Maiden+Orange'),
    array('label' => 'Mako', 'value' => 'Mako'),
    array('label' => 'Marck Script', 'value' => 'Marck+Script'),
    array('label' => 'Marvel', 'value' => 'Marvel'),
    array('label' => 'Mate SC', 'value' => 'Mate+SC'),
    array('label' => 'Mate', 'value' => 'Mate'),
    array('label' => 'Maven Pro', 'value' => 'Maven+Pro'),
    array('label' => 'Meddon', 'value' => 'Meddon'),
    array('label' => 'MedievalSharp', 'value' => 'MedievalSharp'),
    array('label' => 'Megrim', 'value' => 'Megrim'),
    array('label' => 'Merienda One', 'value' => 'Merienda+One'),
    array('label' => 'Merriweather', 'value' => 'Merriweather'),
    array('label' => 'Metrophobic', 'value' => 'Metrophobic'),
    array('label' => 'Michroma', 'value' => 'Michroma'),
    array('label' => 'Miltonian Tattoo', 'value' => 'Miltonian+Tattoo'),
    array('label' => 'Miltonian', 'value' => 'Miltonian'),
    array('label' => 'Miss Fajardose', 'value' => 'Miss+Fajardose'),
    array('label' => 'Miss Saint Delafield', 'value' => 'Miss+Saint+Delafield'),
    array('label' => 'Modern Antiqua', 'value' => 'Modern+Antiqua'),
    array('label' => 'Molengo', 'value' => 'Molengo'),
    array('label' => 'Monofett', 'value' => 'Monofett'),
    array('label' => 'Monoton', 'value' => 'Monoton'),
    array('label' => 'Monsieur La Doulaise', 'value' => 'Monsieur+La+Doulaise'),
    array('label' => 'Montez', 'value' => 'Montez'),
    array('label' => 'Montserrat', 'value' => 'Montserrat'),
    array('label' => 'Mountains of Christmas', 'value' => 'Mountains+of+Christmas'),
    array('label' => 'Mr Bedford', 'value' => 'Mr+Bedford'),
    array('label' => 'Mr Dafoe', 'value' => 'Mr+Dafoe'),
    array('label' => 'Mr De Haviland', 'value' => 'Mr+De+Haviland'),
    array('label' => 'Mrs Sheppards', 'value' => 'Mrs+Sheppards'),
    array('label' => 'Muli', 'value' => 'Muli'),
    array('label' => 'Neucha', 'value' => 'Neucha'),
    array('label' => 'Neuton', 'value' => 'Neuton'),
    array('label' => 'News Cycle', 'value' => 'News+Cycle'),
    array('label' => 'Niconne', 'value' => 'Niconne'),
    array('label' => 'Nixie One', 'value' => 'Nixie+One'),
    array('label' => 'Nobile', 'value' => 'Nobile'),
    array('label' => 'Nosifer Caps', 'value' => 'Nosifer+Caps'),
    array('label' => 'Nothing You Could Do', 'value' => 'Nothing+You+Could+Do'),
    array('label' => 'Nova Cut', 'value' => 'Nova+Cut'),
    array('label' => 'Nova Flat', 'value' => 'Nova+Flat'),
    array('label' => 'Nova Mono', 'value' => 'Nova+Mono'),
    array('label' => 'Nova Oval', 'value' => 'Nova+Oval'),
    array('label' => 'Nova Round', 'value' => 'Nova+Round'),
    array('label' => 'Nova Script', 'value' => 'Nova+Script'),
    array('label' => 'Nova Slim', 'value' => 'Nova+Slim'),
    array('label' => 'Nova Square', 'value' => 'Nova+Square'),
    array('label' => 'Numans', 'value' => 'Numans'),
    array('label' => 'Nunito', 'value' => 'Nunito'),
    array('label' => 'Old Standard TT', 'value' => 'Old+Standard+TT'),
    array('label' => 'Open Sans Condensed', 'value' => 'Open+Sans+Condensed'),
    array('label' => 'Open Sans', 'value' => 'Open+Sans'),
    array('label' => 'Orbitron', 'value' => 'Orbitron'),
    array('label' => 'Oswald', 'value' => 'Oswald'),
    array('label' => 'Over the Rainbow', 'value' => 'Over+the+Rainbow'),
    array('label' => 'Ovo', 'value' => 'Ovo'),
    array('label' => 'PT Sans Caption', 'value' => 'PT+Sans+Caption'),
    array('label' => 'PT Sans Narrow', 'value' => 'PT+Sans+Narrow'),
    array('label' => 'PT Sans', 'value' => 'PT+Sans'),
    array('label' => 'PT Serif Caption', 'value' => 'PT+Serif+Caption'),
    array('label' => 'PT Serif', 'value' => 'PT+Serif'),
    array('label' => 'Pacifico', 'value' => 'Pacifico'),
    array('label' => 'Passero One', 'value' => 'Passero+One'),
    array('label' => 'Patrick Hand', 'value' => 'Patrick+Hand'),
    array('label' => 'Paytone One', 'value' => 'Paytone+One'),
    array('label' => 'Permanent Marker', 'value' => 'Permanent+Marker'),
    array('label' => 'Petrona', 'value' => 'Petrona'),
    array('label' => 'Philosopher', 'value' => 'Philosopher'),
    array('label' => 'Piedra', 'value' => 'Piedra'),
    array('label' => 'Pinyon Script', 'value' => 'Pinyon+Script'),
    array('label' => 'Play', 'value' => 'Play'),
    array('label' => 'Playfair Display', 'value' => 'Playfair+Display'),
    array('label' => 'Podkova', 'value' => 'Podkova'),
    array('label' => 'Poller One', 'value' => 'Poller+One'),
    array('label' => 'Poly', 'value' => 'Poly'),
    array('label' => 'Pompiere', 'value' => 'Pompiere'),
    array('label' => 'Prata', 'value' => 'Prata'),
    array('label' => 'Prociono', 'value' => 'Prociono'),
    array('label' => 'Puritan', 'value' => 'Puritan'),
    array('label' => 'Quattrocento Sans', 'value' => 'Quattrocento+Sans'),
    array('label' => 'Quattrocento', 'value' => 'Quattrocento'),
    array('label' => 'Questrial', 'value' => 'Questrial'),
    array('label' => 'Quicksand', 'value' => 'Quicksand'),
    array('label' => 'Radley', 'value' => 'Radley'),
    array('label' => 'Raleway', 'value' => 'Raleway'),
    array('label' => 'Rammetto One', 'value' => 'Rammetto+One'),
    array('label' => 'Rancho', 'value' => 'Rancho'),
    array('label' => 'Rationale', 'value' => 'Rationale'),
    array('label' => 'Redressed', 'value' => 'Redressed'),
    array('label' => 'Reenie Beanie', 'value' => 'Reenie+Beanie'),
    array('label' => 'Ribeye Marrow', 'value' => 'Ribeye+Marrow'),
    array('label' => 'Ribeye', 'value' => 'Ribeye'),
    array('label' => 'Righteous', 'value' => 'Righteous'),
    array('label' => 'Rochester', 'value' => 'Rochester'),
    array('label' => 'Roboto', 'value' => 'Roboto'),
    array('label' => 'Rock Salt', 'value' => 'Rock+Salt'),
    array('label' => 'Rokkitt', 'value' => 'Rokkitt'),
    array('label' => 'Rosario', 'value' => 'Rosario'),
    array('label' => 'Ruslan Display', 'value' => 'Ruslan+Display'),
    array('label' => 'Salsa', 'value' => 'Salsa'),
    array('label' => 'Sancreek', 'value' => 'Sancreek'),
    array('label' => 'Sansita One', 'value' => 'Sansita+One'),
    array('label' => 'Satisfy', 'value' => 'Satisfy'),
    array('label' => 'Schoolbell', 'value' => 'Schoolbell'),
    array('label' => 'Shadows Into Light', 'value' => 'Shadows+Into+Light'),
    array('label' => 'Shanti', 'value' => 'Shanti'),
    array('label' => 'Short Stack', 'value' => 'Short+Stack'),
    array('label' => 'Sigmar One', 'value' => 'Sigmar+One'),
    array('label' => 'Signika Negative', 'value' => 'Signika+Negative'),
    array('label' => 'Signika', 'value' => 'Signika'),
    array('label' => 'Six Caps', 'value' => 'Six+Caps'),
    array('label' => 'Slackey', 'value' => 'Slackey'),
    array('label' => 'Smokum', 'value' => 'Smokum'),
    array('label' => 'Smythe', 'value' => 'Smythe'),
    array('label' => 'Sniglet', 'value' => 'Sniglet'),
    array('label' => 'Snippet', 'value' => 'Snippet'),
    array('label' => 'Sorts Mill Goudy', 'value' => 'Sorts+Mill+Goudy'),
    array('label' => 'Special Elite', /* */ 'value' => 'Special+Elite'),
    array('label' => 'Spinnaker', 'value' => 'Spinnaker'),
    array('label' => 'Spirax', 'value' => 'Spirax'),
    array('label' => 'Stardos Stencil', /* */ 'value' => 'Stardos+Stencil'),
    array('label' => 'Sue Ellen Francisco', /* */ 'value' => 'Sue+Ellen+Francisco'),
    array('label' => 'Sunshiney', 'value' => 'Sunshiney'),
    array('label' => 'Supermercado One', 'value' => 'Supermercado+One'),
    array('label' => 'Swanky and Moo Moo', 'value' => 'Swanky+and+Moo+Moo'),
    array('label' => 'Syncopate', 'value' => 'Syncopate'),
    array('label' => 'Tangerine', 'value' => 'Tangerine'),
    array('label' => 'Tenor Sans', 'value' => 'Tenor+Sans'),
    array('label' => 'Terminal Dosis', 'value' => 'Terminal+Dosis'),
    array('label' => 'The Girl Next Door', 'value' => 'The+Girl+Next+Door'),
    array('label' => 'Tienne', 'value' => 'Tienne'),
    array('label' => 'Titillium Web', 'value' => 'Titillium+Web'),
    array('label' => 'Tinos', 'value' => 'Tinos'),
    array('label' => 'Tulpen One', 'value' => 'Tulpen+One'),
    array('label' => 'Ubuntu Condensed', 'value' => 'Ubuntu+Condensed'),
    array('label' => 'Ubuntu Mono', 'value' => 'Ubuntu+Mono'),
    array('label' => 'Ubuntu', 'value' => 'Ubuntu'),
    array('label' => 'Ultra', 'value' => 'Ultra'),
    array('label' => 'UnifrakturCook', 'value' => 'UnifrakturCook'),
    array('label' => 'UnifrakturMaguntia', 'value' => 'UnifrakturMaguntia'),
    array('label' => 'Unkempt', 'value' => 'Unkempt'),
    array('label' => 'Unlock', 'value' => 'Unlock'),
    array('label' => 'Unna', 'value' => 'Unna'),
    array('label' => 'VT323', 'value' => 'VT323'),
    array('label' => 'Varela Round', 'value' => 'Varela+Round'),
    array('label' => 'Varela', 'value' => 'Varela'),
    array('label' => 'Vast Shadow', 'value' => 'Vast+Shadow'),
    array('label' => 'Vibur', 'value' => 'Vibur'),
    array('label' => 'Vidaloka', 'value' => 'Vidaloka'),
    array('label' => 'Volkhov', 'value' => 'Volkhov'),
    array('label' => 'Vollkorn', 'value' => 'Vollkorn'),
    array('label' => 'Voltaire', 'value' => 'Voltaire'),
    array('label' => 'Waiting for the Sunrise', 'value' => 'Waiting+for+the+Sunrise'),
    array('label' => 'Wallpoet', 'value' => 'Wallpoet'),
    array('label' => 'Walter Turncoat', 'value' => 'Walter+Turncoat'),
    array('label' => 'Wire One', 'value' => 'Wire+One'),
    array('label' => 'Yanone Kaffeesatz', 'value' => 'Yanone+Kaffeesatz'),
    array('label' => 'Yellowtail', 'value' => 'Yellowtail'),
    array('label' => 'Yeseva One', 'value' => 'Yeseva+One'),
    array('label' => 'Zeyada', 'value' => 'Zeyada')
);

/**
 * Initialize the custom Theme Options.
 */
add_action('init', 'custom_theme_options');

function custom_theme_options() {
    
    global $google_fonts;

    /* OptionTree is not loaded yet, or this is not an admin request */
    if (!function_exists('ot_settings_id') || !is_admin())
        return false;

    /**
     * Get a copy of the saved settings array. 
     */
    $saved_settings = get_option(ot_settings_id(), array());

    /**
     * Custom settings array that will eventually be 
     * passes to the OptionTree Settings API Class.
     */
    $custom_settings = array(
        'contextual_help' => array(
        ),
        'sections' => array(
            array(
                'id' => 'general',
                'title' => 'General'
            ),
            array(
                'id' => 'layoutmgt',
                'title' => 'Layout Management'
            ),
            array(
                'id' => 'Tpgrphy',
                'title' => 'Typography'
            ),
            array(
                'id' => 'socialicon',
                'title' => 'Social icons'
            ),
            array(
                'id' => 'blogsettting',
                'title' => 'Blog'
            )
        ),
        'settings' => array(
            array(
                'id' => 'my_name',
                'label' => 'Your name',
                'desc' => 'Type your name here',
                'std' => '',
                'type' => 'text',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'my_subtitle',
                'label' => 'Subtitle',
                'desc' => 'Type a subtitle (university name , Phd etc...)',
                'std' => '',
                'type' => 'text',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'my_location',
                'label' => 'Location',
                'desc' => 'Type your location',
                'std' => '',
                'type' => 'text',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'sidebar_text1',
                'label' => 'Sidebar border text 1',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),array(
                'id' => 'sidebar_text2',
                'label' => 'Sidebar border text 2',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'perso_pic_upload',
                'label' => 'Your Personal Photo',
                'desc' => 'Upload your personal photo here',
                'std' => '',
                'type' => 'upload',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'cv_attachment_id',
                'label' => 'Your CV file',
                'desc' => 'Upload your cv file',
                'std' => '',
                'type' => 'upload',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'header_news',
                'label' => 'Header news',
                'desc' => 'Header news here',
                'std' => '',
                'type' => 'list-item',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and',
                'settings' => array(
                    array(
                        'id' => 'header_news_content',
                        'label' => 'Header news item',
                        'desc' => '',
                        'std' => '',
                        'type' => 'textarea-simple',
                        'rows' => '10',
                        'post_type' => '',
                        'taxonomy' => '',
                        'min_max_step' => '',
                        'class' => '',
                        'condition' => '',
                        'operator' => 'and'
                    )
                )
            ),
            array(
                'id' => 'contact_on_off',
                'label' => 'Show contact page shortcut',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'contact_page_n',
                'label' => 'Contact page number',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'general',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'contact_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'main_colorpicker',
                'label' => 'Main theme color',
                'desc' => '',
                'std' => '',
                'type' => 'colorpicker',
                'section' => 'layoutmgt',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'sectionwidth',
                'label' => 'Sections widths',
                'desc' => 'Section widths in px (without px)',
                'std' => '',
                'type' => 'text',
                'section' => 'layoutmgt',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
             array(
        'id'          => 'pulse_loader',
        'label'       => 'Show loader',
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'layoutmgt',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
             array(
        'id'          => 'pulse_arrow',
        'label'       => 'Show Navigation arrows',
        'desc'        => '',
        'std'         => 'on',
        'type'        => 'on-off',
        'section'     => 'layoutmgt',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
                'id' => 'facebook_on_off',
                'label' => 'Facebook',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'facebook_url',
                'label' => 'Your facebook url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'facebook_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'twitter_on_off',
                'label' => 'Twitter',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'twitter_url',
                'label' => 'Your twitter url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'twitter_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'googleplus_on_off',
                'label' => 'Google plus',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'googleplus_url',
                'label' => 'Your Google plus url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'googleplus_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'youtube_on_off',
                'label' => 'Youtube',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'youtube_url',
                'label' => 'Your youtube url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'youtube_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'linkedin_on_off',
                'label' => 'Linkedin',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'linkedin_url',
                'label' => 'Your linkedin url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'linkedin_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'flickr_on_off',
                'label' => 'Flickr',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'flickr_url',
                'label' => 'Your flickr url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'flickr_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'dribbble_on_off',
                'label' => 'Dribbble',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'dribbble_url',
                'label' => 'Your dribbble url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'dribbble_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'instagram_on_off',
                'label' => 'Instagram',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'instagram_url',
                'label' => 'Your instagram url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'instagram_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'github_on_off',
                'label' => 'Github',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'github_url',
                'label' => 'Your github url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'github_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'vimeo_on_off',
                'label' => 'Vimeo',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'vimeo_url',
                'label' => 'Your vimeo url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'vimeo_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'vk_on_off',
                'label' => 'Vk',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'vk_url',
                'label' => 'Your vk url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'vk_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'foursquare_on_off',
                'label' => 'Foursquare',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'foursquare_url',
                'label' => 'Your foursquare url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'foursquare_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
                'id' => 'tumblr_on_off',
                'label' => 'Tumblr',
                'desc' => '',
                'std' => 'off',
                'type' => 'on-off',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => '',
                'operator' => 'and'
            ),
            array(
                'id' => 'tumblr_url',
                'label' => 'Your tumblr url',
                'desc' => '',
                'std' => '',
                'type' => 'text',
                'section' => 'socialicon',
                'rows' => '',
                'post_type' => '',
                'taxonomy' => '',
                'min_max_step' => '',
                'class' => '',
                'condition' => 'tumblr_on_off:is(on)',
                'operator' => 'and'
            ),
            array(
        'id'          => 'pulse_favicon',
        'label'       => 'Site favicon',
        'desc'        => 'Upload a 16x16 or 32x32 .png or .ico file',
        'std'         => '',
        'type'        => 'upload',
        'section'     => 'layoutmgt',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
        'id'          => 'pulse_body_font',
        'label'       => 'Pulse Body font',
        'desc'        => 'Choose font for body ( Default is Titillium Web).',
        'std'         => '',
        'type'        => 'select',
        'section'     => 'Tpgrphy',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'choices'     => $google_fonts
      ),
            array(
        'id'          => 'pulse_heading_font',
        'label'       => 'Pulse Heading font',
        'desc'        => 'Choose font for heading ( Default is Titillium Web).',
        'std'         => '',
        'type'        => 'select',
        'section'     => 'Tpgrphy',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'choices'     => $google_fonts
      ),
           array(
        'id'          => 'glbl_size',
        'label'       => 'Global font size',
        'desc'        => 'Default is 15 px',
        'std'         => '15',
        'type'        => 'numeric-slider',
        'section'     => 'Tpgrphy',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
        'id'          => 'sections_title',
        'label'       => 'Big title font size',
        'desc'        => 'Default is 31 px',
        'std'         => '31',
        'type'        => 'numeric-slider',
        'section'     => 'Tpgrphy',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'sml_title',
        'label'       => 'small title font size',
        'desc'        => 'Default is 16 px',
        'std'         => '16',
        'type'        => 'numeric-slider',
        'section'     => 'Tpgrphy',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
      array(
        'id'          => 'menu_ftsize',
        'label'       => 'Menu font size',
        'desc'        => 'Default is 15 px',
        'std'         => '15',
        'type'        => 'numeric-slider',
        'section'     => 'Tpgrphy',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
        'id'          => 'blog_facebook',
        'label'       => 'Show share post on facebook button',
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'blogsettting',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
        'id'          => 'blog_twitter',
        'label'       => 'Show share post on twitter button',
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'blogsettting',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
        'id'          => 'blog_googleplus',
        'label'       => 'Show share post on google plus button',
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'blogsettting',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
        'id'          => 'blog_pinterest',
        'label'       => 'Show share post on pinterest button',
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'blogsettting',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
        'id'          => 'blog_authorbox',
        'label'       => 'Show author box',
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'blogsettting',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
        'id'          => 'blog_postnav',
        'label'       => 'Show post naviguation',
        'desc'        => '',
        'std'         => 'off',
        'type'        => 'on-off',
        'section'     => 'blogsettting',
        'rows'        => '',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      ),
            array(
        'id'          => 'demo_css',
        'label'       => 'CSS Customizations',
        'desc'        => 'Paste your custom CSS code , In some cases, the !important tag may be needed.',
        'std'         => '',
        'type'        => 'css',
        'section'     => 'layoutmgt',
        'rows'        => '20',
        'post_type'   => '',
        'taxonomy'    => '',
        'min_max_step'=> '',
        'class'       => '',
        'condition'   => '',
        'operator'    => 'and'
      )
        )
    );


    /* allow settings to be filtered before saving */
    $custom_settings = apply_filters(ot_settings_id() . '_args', $custom_settings);

    /* settings are not the same update the DB */
    if ($saved_settings !== $custom_settings) {
        update_option(ot_settings_id(), $custom_settings);
    }

    /* Lets OptionTree know the UI Builder is being overridden */
    global $ot_has_custom_theme_options;
    $ot_has_custom_theme_options = true;
}
